version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - '35000:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db


